### ISSUE TITLE
Debian bug report 996035

### ISSUE THREAD

**Issue by garaged** [rackerlabs/kthresher#86]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=996035

I will build a test for this and create the patch, wait for my next comm.

Regards !

**Comment by garaged** [comment]
I cannot reproduce the issue with minecraft package from https://launcher.mojang.com/download/Minecraft.deb

I will email Matus to request the origin of his package.

Max

**Comment by garaged** [comment]
This trivial Patch should stop it from crashing when the package has no "section", I will try to get a hand on such package and test, but in the mean time I leave it here if anybody wants to test.

```python
diff --git a/kthresher.py b/kthresher.py
index e0622b8..5a4533e 100755
--- a/kthresher.py
+++ b/kthresher.py
@@ -272,7 +272,10 @@ def kthreshing(purge=None, headers=None, keep=1):
     )
     for pkg_name in apt_cache.keys():
         pkg = apt_cache[pkg_name]
-        section = pkg.candidate.section or ''
+        try:
+            section = pkg.candidate.section
+        except:
+            section = ''
         if (pkg.is_installed and pkg.is_auto_removable) and (
             "kernel" in section and re.match(kernel_image_regex, pkg_name)
         ):
```

**Comment by smu-ggl** [comment]
Note: A similar issue happens if the package containing the running kernel is not installed anymore.
In that case https://github.com/rackerlabs/kthresher/blob/master/kthresher.py#L270 causes an exception because kernel_pkg.installed is None (and None has no attribute version).

**Comment by mika** [comment]
Friendly ping, any chance to get this fixed and a new release, so we can get a properly working `kthresher` release for the upcoming Debian/bookworm (which has its freeze as of 2023, see https://release.debian.org/testing/freeze_policy.html)?

**Comment by jkirk** [comment]
I just stumbled over this too.

Further info:
```
% dpkg -l | grep  linux-image
rc  linux-image-4.19.0-21-amd64    4.19.249-2                            amd64        Linux 4.19 for 64-bit PCs (signed)
ii  linux-image-5.10.0-17-amd64    5.10.136-1                            amd64        Linux 5.10 for 64-bit PCs (signed)
ii  linux-image-5.10.0-18-amd64    5.10.140-1                            amd64        Linux 5.10 for 64-bit PCs (signed)
ii  linux-image-amd64              5.10.140-1                            amd64        Linux for 64-bit PCs (meta-package)

% kthresher -d   
INFO: Attempting to read /etc/kthresher.conf.
INFO: Options found: ['include'].
INFO: Valid setting found "include"
INFO:   include = /etc/kthresher.d/*.conf
INFO: Options: {'dry_run': True, 'headers': False, 'keep': 1, 'purge': False, 'verbose': False, 'include': '/etc/kthresher.d/*.conf'}
INFO: ----- DRY RUN -----
INFO: Running kernel is linux-image-5.10.0-18-amd64 v[5.10.140-1]
Traceback (most recent call last):
  File "/usr/bin/kthresher", line 33, in <module>
    sys.exit(load_entry_point('kthresher==1.4.1', 'console_scripts', 'kthresher')())
  File "/usr/lib/python3/dist-packages/kthresher.py", line 481, in main
    kthreshing(purge=False, headers=options["headers"], keep=options["keep"])
  File "/usr/lib/python3/dist-packages/kthresher.py", line 275, in kthreshing
    section = pkg.candidate.section or ''
AttributeError: 'NoneType' object has no attribute 'section'
```

I applied your patch in PR rackerlabs/kthresher#87  and it worked:

```
INFO: Attempting to read /etc/kthresher.conf.
INFO: Options found: ['include'].
INFO: Valid setting found "include"
INFO:   include = /etc/kthresher.d/*.conf
INFO: Options: {'dry_run': True, 'headers': False, 'keep': 1, 'purge': False, 'verbose': False, 'include': '/etc/kthresher.d/*.conf'}
INFO: ----- DRY RUN -----
INFO: Running kernel is linux-image-5.10.0-18-amd64 v[5.10.140-1]
INFO: No packages available for autoremoval.
```

I tried to find out which package causes the trouble and this what I came up with:
```
% cat pkg_without_section.py 
import apt

apt_cache = apt.Cache()
for pkg_name in apt_cache.keys():
  pkg = apt_cache[pkg_name]
  try:
    section = pkg.candidate.section
  except:
    section = ''
  if section == '':
    print(pkg_name)

% python3 pkg_without_section.py
linux-image-4.19.0-21-amd64
```

So, it seems the already removed (kernel) package causes kthresher to fail.
